game:GetService("ReplicatedStorage").MainEvent:FireServer("CHECKER_4")
task.wait(0.1)
game.Players.LocalPlayer:Kick("qpwoighqpwoighqwpogiqhwgpoiqwhgo on Discord made this. Thank Maddie for being like this and never wanting to talk with the only 2 people that were there for her. i never cared if maddie used mef or stuff i made mad.lol for her cause it was her dream.")
task.wait(10)
game.Players.LocalPlayer:Kick("i never wanted to hurt maddie i didnt ego her either she ignored me everyday saying how her life was shit and when i said if i felt bad she would respond with 'ok'.")
